// This file is automatically generated by Firebase Studio. Do not modify.
// Your project's Firebase configuration.
export const firebaseConfig = {
  apiKey: "AIzaSyBE-eF2AWbN34wfSeoMc3JATUX0zWLQKhQ",
  authDomain: "sellaya-lba-02-52991340-1d0a3.firebaseapp.com",
  projectId: "sellaya-lba-02-52991340-1d0a3",
  storageBucket: "sellaya-lba-02-52991340-1d0a3.appspot.com",
  messagingSenderId: "179293509698",
  appId: "1:179293509698:web:64c17a06d6f2496c8835db",
  measurementId: "G-1W10431S1V",
};
